version: '3.8'
services:
  mongoDB:
    image: 'mongo'
    ports:
      - 27017:27017 
  backend:
    build: ./backend  
    ports:
      - '4000:4000'
    volumes:
      - ./backend:/app
    depends_on:
      - mongoDB
  frontend:
    build: ./frontend  
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend